USE `cuts_styles_db`;

SET NAMES utf8mb4;

ALTER TABLE `service_chat_messages`
  ADD COLUMN IF NOT EXISTS `delivered_at` DATETIME DEFAULT NULL AFTER `created_at`,
  ADD COLUMN IF NOT EXISTS `read_at` DATETIME DEFAULT NULL AFTER `delivered_at`;

ALTER TABLE `service_chats`
  ADD COLUMN IF NOT EXISTS `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER `last_message_at`;

